import path from "path";
import fs from "fs";
import type { ServerResponse } from "http";
import { REPO_ROOT, CONTENT_DIR, isResponseClosed, KINDS, LANGS, mdDir } from "./util.ts";
import { icons as coreIcons } from "@phosphor-icons/core";

export const ICON_CATALOG_FILE = path.join(REPO_ROOT, "@shared", "icon-catalog.ts");
export const WEB_ICON_MAP_FILE = path.join(REPO_ROOT, "@web", "src", "components", "icon-map.generated.ts");
export const CMS_ICON_MAP_FILE = path.join(REPO_ROOT, "@cms", "src", "components", "icon-map.generated.ts");

const MARKER_PATTERN = /:([A-Z][A-Za-z]+Icon):/g;
const MARKER_SUFFIX = "Icon";

interface CoreEntry {
  readonly name: string;
  readonly pascal_name: string;
  readonly categories?: readonly string[];
  readonly tags?: readonly string[];
}

export interface IconCatalogEntry {
  name: string;
  tags: string[];
  categories: string[];
}

export interface IconsSyncResult {
  usedCount: number;
  mappedCount: number;
  added: string[];
  removed: string[];
  unknown: string[];
  catalogVersion: string;
  catalogRegenerated: boolean;
  webMapChanged: boolean;
  cmsMapChanged: boolean;
}

type LogFn = (line: string) => void;

const coreVersion = (): string => {
  try {
    const pkg = JSON.parse(
      fs.readFileSync(path.join(REPO_ROOT, "node_modules", "@phosphor-icons", "core", "package.json"), "utf8")
    ) as { version?: string };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
};

const toMarker = (entry: CoreEntry): string | null =>
  /^[A-Z][A-Za-z]+$/.test(entry.pascal_name) ? `${entry.pascal_name}${MARKER_SUFFIX}` : null;

function buildCatalog(): IconCatalogEntry[] {
  const seen = new Map<string, IconCatalogEntry>();
  for (const entry of coreIcons as readonly CoreEntry[]) {
    const name = toMarker(entry);
    if (!name || seen.has(name)) continue;
    seen.set(name, {
      name,
      tags: [...(entry.tags ?? [])].filter((tag) => !tag.startsWith("*")),
      categories: [...(entry.categories ?? [])],
    });
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}

function renderCatalog(catalog: IconCatalogEntry[], version: string): string {
  const rows = catalog
    .map(
      (entry) =>
        `  { name: "${entry.name}", tags: ${JSON.stringify(entry.tags)}, categories: ${JSON.stringify(entry.categories)} },`
    )
    .join("\n");
  return `// Generated by \`npm run sync-icons\` - DO NOT EDIT.
// Source: @phosphor-icons/core@${version} (Phosphor icon metadata: names, tags, categories).

export interface IconCatalogEntry {
  name: string;
  tags: string[];
  categories: string[];
}

// prettier-ignore
export const ICON_CATALOG: IconCatalogEntry[] = [
${rows}
];

const knownSet: ReadonlySet<string> = new Set(ICON_CATALOG.map((icon) => icon.name));

export function isKnownIcon(name: string): boolean {
  return knownSet.has(name);
}
`;
}

function renderComponentMap(names: string[]): string {
  const imports = names.length > 0 ? `import { ${names.join(", ")} } from "@phosphor-icons/react";\n\n` : "";
  const rows = names.length > 0 ? names.map((name) => `  ${name},`).join("\n") : "  // no icons referenced yet";
  return `// Generated by \`npm run sync-icons\` - DO NOT EDIT.

${imports}import type { ComponentType } from "react";

export const ICON_COMPONENTS: Record<string, ComponentType<{ className?: string }>> = {
${rows}
};
`;
}

async function formatSource(source: string, filePath: string): Promise<string> {
  try {
    const prettier = await import("prettier");
    return await prettier.format(source, { filepath: filePath });
  } catch {
    return source;
  }
}

async function readFileIfExists(filePath: string): Promise<string | null> {
  try {
    return await fs.promises.readFile(filePath, "utf8");
  } catch {
    return null;
  }
}

async function writeFileStable(filePath: string, next: string): Promise<boolean> {
  const current = await readFileIfExists(filePath);
  if (current === next) return false;
  await fs.promises.writeFile(filePath, next, "utf8");
  return true;
}

function mapKeysFromRendered(source: string): string[] {
  const bodyStart = source.indexOf("= {");
  const bodyEnd = source.lastIndexOf("};");
  if (bodyStart < 0 || bodyEnd < 0) return [];
  return [...source.slice(bodyStart + 3, bodyEnd).matchAll(/\b([A-Z][A-Za-z]+Icon)\b/g)].map((m) => m[1]);
}

export async function scanUsedMarkers(log: LogFn): Promise<Set<string>> {
  const markers = new Set<string>();
  let files = 0;
  for (const lang of LANGS) {
    for (const kind of KINDS) {
      // Scan metadata JSON (may still have some markers in titles/descriptions)
      const jsonPath = path.join(CONTENT_DIR, lang, `${kind}.json`);
      try {
        const data = JSON.parse(await fs.promises.readFile(jsonPath, "utf8"));
        files += 1;
        const visit = (node: unknown): void => {
          if (typeof node === "string") {
            for (const match of node.matchAll(MARKER_PATTERN)) markers.add(match[1]);
          } else if (Array.isArray(node)) {
            for (const item of node) visit(item);
          } else if (typeof node === "object" && node !== null) {
            for (const value of Object.values(node)) visit(value);
          }
        };
        visit(data);
      } catch {
        // continue to md scan
      }
      // Scan md files for icon markers
      const dir = mdDir(kind, lang);
      try {
        const mdFiles = await fs.promises.readdir(dir);
        for (const file of mdFiles) {
          if (!file.endsWith(".md")) continue;
          const content = await fs.promises.readFile(path.join(dir, file), "utf8");
          files += 1;
          for (const match of content.matchAll(MARKER_PATTERN)) markers.add(match[1]);
        }
      } catch {
        // dir may not exist
      }
    }
  }
  log(`scanned ${files} content file(s): ${markers.size} unique icon reference(s)`);
  return markers;
}

const isRenderable = (value: unknown): boolean =>
  typeof value === "function" || (typeof value === "object" && value !== null && "$$typeof" in value);

async function loadReactExportNames(log: LogFn): Promise<Set<string> | null> {
  try {
    const mod = (await import("@phosphor-icons/react")) as Record<string, unknown>;
    return new Set(Object.keys(mod).filter((key) => isRenderable(mod[key])));
  } catch (err) {
    log(`note: could not cross-check against @phosphor-icons/react (${(err as Error).message.split("\n")[0]})`);
    return null;
  }
}

async function ensureCatalog(
  force: boolean,
  log: LogFn
): Promise<{ catalog: IconCatalogEntry[]; regenerated: boolean }> {
  const catalog = buildCatalog();
  const version = coreVersion();
  const current = await readFileIfExists(ICON_CATALOG_FILE);
  if (force || current === null || !current.includes(`@phosphor-icons/core@${version}`)) {
    await writeFileStable(ICON_CATALOG_FILE, await formatSource(renderCatalog(catalog, version), ICON_CATALOG_FILE));
    log(`catalog regenerated: ${catalog.length} icons (@phosphor-icons/core@${version})`);
    return { catalog, regenerated: true };
  }
  log(`catalog up-to-date (${catalog.length} icons, @phosphor-icons/core@${version})`);
  return { catalog, regenerated: false };
}

export async function syncIcons(log: LogFn = () => {}, opts: { force?: boolean } = {}): Promise<IconsSyncResult> {
  const { catalog, regenerated: catalogRegenerated } = await ensureCatalog(opts.force ?? false, log);

  const markers = await scanUsedMarkers(log);

  const exports = await loadReactExportNames(log);
  const known = new Set(catalog.map((entry) => entry.name));
  const unknown = [...markers].filter((name) => !known.has(name)).sort();
  if (unknown.length > 0) log(`warning: unknown icon placeholder(s) in content: ${unknown.join(", ")}`);

  const mapped = [...markers].filter((name) => known.has(name)).sort((a, b) => a.localeCompare(b));
  if (exports) {
    const missing = mapped.filter((name) => !exports.has(name));
    if (missing.length > 0) log(`warning: installed @phosphor-icons/react lacks: ${missing.join(", ")}`);
  }

  const previous = await readFileIfExists(WEB_ICON_MAP_FILE);
  const writable = exports ? mapped.filter((name) => exports.has(name)) : mapped;
  const added = writable.filter((name) => !previousKeys(previous).includes(name));
  const removed = previousKeys(previous).filter((name) => !writable.includes(name));

  const webMapChanged = await writeFileStable(
    WEB_ICON_MAP_FILE,
    await formatSource(renderComponentMap(writable), WEB_ICON_MAP_FILE)
  );
  log(
    webMapChanged
      ? `web icon map updated: ${writable.length} icon(s)` +
          (added.length > 0 ? ` (+${added.join(", ")})` : "") +
          (removed.length > 0 ? ` (-${removed.join(", ")})` : "")
      : `web icon map unchanged (${writable.length} icon(s))`
  );

  const cmsWritable = exports
    ? catalog.map((entry) => entry.name).filter((name) => exports.has(name))
    : catalog.map((entry) => entry.name);
  const cmsMapChanged = await writeFileStable(
    CMS_ICON_MAP_FILE,
    await formatSource(renderComponentMap(cmsWritable.sort((a, b) => a.localeCompare(b))), CMS_ICON_MAP_FILE)
  );
  log(`cms icon map ${cmsMapChanged ? "regenerated" : "unchanged"} (${cmsWritable.length} icons)`);

  return {
    usedCount: markers.size,
    mappedCount: writable.length,
    added,
    removed,
    unknown,
    catalogVersion: coreVersion(),
    catalogRegenerated,
    webMapChanged,
    cmsMapChanged,
  };
}

function previousKeys(source: string | null): string[] {
  return source ? mapKeysFromRendered(source) : [];
}

let running = false;

export function runIconsSync(res: ServerResponse, opts: { force?: boolean } = {}): void {
  if (running) {
    res.writeHead(409, { "Content-Type": "text/plain" });
    res.end("icon sync already running");
    return;
  }
  running = true;

  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-store",
    Connection: "keep-alive",
  });

  const send = (event: string, data: string): void => {
    if (isResponseClosed(res)) return;
    res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
  };

  void (async () => {
    try {
      const result = await syncIcons((line) => send("log", line), opts);
      send("log", `done: ${result.mappedCount} mapped, ${result.unknown.length} unknown placeholder(s)`);
      send("done", result.unknown.length > 0 ? "completed-with-warnings" : "ok");
    } catch (err) {
      send("log", `failed: ${(err as Error).message}`);
      send("done", "error");
    } finally {
      running = false;
      res.end();
    }
  })();

  res.on("close", () => {
    running = false;
  });
}
