// Generated by `npm run sync-icons` - DO NOT EDIT.

import {
  ArrowsClockwiseIcon,
  CpuIcon,
  DeviceMobileIcon,
  DownloadIcon,
  FolderIcon,
  GearIcon,
  GlobeIcon,
  HouseIcon,
  ImageIcon,
  KeyboardIcon,
  NoteIcon,
  PushPinIcon,
  RocketIcon,
  ScissorsIcon,
  SparkleIcon,
  StarIcon,
  TelevisionIcon,
  UsersIcon,
  WarningIcon,
  WrenchIcon,
} from "@phosphor-icons/react";

import type { ComponentType } from "react";

export const ICON_COMPONENTS: Record<
  string,
  ComponentType<{ className?: string }>
> = {
  ArrowsClockwiseIcon,
  CpuIcon,
  DeviceMobileIcon,
  DownloadIcon,
  FolderIcon,
  GearIcon,
  GlobeIcon,
  HouseIcon,
  ImageIcon,
  KeyboardIcon,
  NoteIcon,
  PushPinIcon,
  RocketIcon,
  ScissorsIcon,
  SparkleIcon,
  StarIcon,
  TelevisionIcon,
  UsersIcon,
  WarningIcon,
  WrenchIcon,
};
