/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as R404RouteImport } from './routes/404'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangArchiveRouteImport } from './routes/$lang/archive'
import { Route as LangCreditsRouteImport } from './routes/$lang/credits'
import { Route as LangModrinthRouteImport } from './routes/$lang/modrinth'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as LangPostSlugRouteImport } from './routes/$lang/post.$slug'
import { Route as LangWikiIndexRouteImport } from './routes/$lang/wiki/index'
import { Route as LangWikiSlugRouteImport } from './routes/$lang/wiki.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any).lazy(() => import('./routes/$lang/about.lazy').then((d) => d.Route))
const LangArchiveRoute = LangArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => LangRoute,
} as any).lazy(() => import('./routes/$lang/archive.lazy').then((d) => d.Route))
const LangCreditsRoute = LangCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => LangRoute,
} as any).lazy(() => import('./routes/$lang/credits.lazy').then((d) => d.Route))
const LangModrinthRoute = LangModrinthRouteImport.update({
  id: '/modrinth',
  path: '/modrinth',
  getParentRoute: () => LangRoute,
} as any).lazy(() =>
  import('./routes/$lang/modrinth.lazy').then((d) => d.Route),
)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/post.$slug.lazy').then((d) => d.Route))
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/wiki.$slug.lazy').then((d) => d.Route))
const LangPostSlugRoute = LangPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => LangRoute,
} as any).lazy(() =>
  import('./routes/$lang/post.$slug.lazy').then((d) => d.Route),
)
const LangWikiIndexRoute = LangWikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => LangRoute,
} as any).lazy(() =>
  import('./routes/$lang/wiki/index.lazy').then((d) => d.Route),
)
const LangWikiSlugRoute = LangWikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => LangRoute,
} as any).lazy(() =>
  import('./routes/$lang/wiki.$slug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/404': typeof R404Route
  '/$lang/about': typeof LangAboutRoute
  '/$lang/archive': typeof LangArchiveRoute
  '/$lang/credits': typeof LangCreditsRoute
  '/$lang/modrinth': typeof LangModrinthRoute
  '/post/$slug': typeof PostSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/post/$slug': typeof LangPostSlugRoute
  '/$lang/wiki/$slug': typeof LangWikiSlugRoute
  '/$lang/wiki/': typeof LangWikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/$lang/about': typeof LangAboutRoute
  '/$lang/archive': typeof LangArchiveRoute
  '/$lang/credits': typeof LangCreditsRoute
  '/$lang/modrinth': typeof LangModrinthRoute
  '/post/$slug': typeof PostSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/post/$slug': typeof LangPostSlugRoute
  '/$lang/wiki/$slug': typeof LangWikiSlugRoute
  '/$lang/wiki': typeof LangWikiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/404': typeof R404Route
  '/$lang/about': typeof LangAboutRoute
  '/$lang/archive': typeof LangArchiveRoute
  '/$lang/credits': typeof LangCreditsRoute
  '/$lang/modrinth': typeof LangModrinthRoute
  '/post/$slug': typeof PostSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/post/$slug': typeof LangPostSlugRoute
  '/$lang/wiki/$slug': typeof LangWikiSlugRoute
  '/$lang/wiki/': typeof LangWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/404'
    | '/$lang/about'
    | '/$lang/archive'
    | '/$lang/credits'
    | '/$lang/modrinth'
    | '/post/$slug'
    | '/wiki/$slug'
    | '/$lang/'
    | '/$lang/post/$slug'
    | '/$lang/wiki/$slug'
    | '/$lang/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/$lang/about'
    | '/$lang/archive'
    | '/$lang/credits'
    | '/$lang/modrinth'
    | '/post/$slug'
    | '/wiki/$slug'
    | '/$lang'
    | '/$lang/post/$slug'
    | '/$lang/wiki/$slug'
    | '/$lang/wiki'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/404'
    | '/$lang/about'
    | '/$lang/archive'
    | '/$lang/credits'
    | '/$lang/modrinth'
    | '/post/$slug'
    | '/wiki/$slug'
    | '/$lang/'
    | '/$lang/post/$slug'
    | '/$lang/wiki/$slug'
    | '/$lang/wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  R404Route: typeof R404Route
  PostSlugRoute: typeof PostSlugRoute
  WikiSlugRoute: typeof WikiSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/archive': {
      id: '/$lang/archive'
      path: '/archive'
      fullPath: '/$lang/archive'
      preLoaderRoute: typeof LangArchiveRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/credits': {
      id: '/$lang/credits'
      path: '/credits'
      fullPath: '/$lang/credits'
      preLoaderRoute: typeof LangCreditsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/modrinth': {
      id: '/$lang/modrinth'
      path: '/modrinth'
      fullPath: '/$lang/modrinth'
      preLoaderRoute: typeof LangModrinthRouteImport
      parentRoute: typeof LangRoute
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/post/$slug': {
      id: '/$lang/post/$slug'
      path: '/post/$slug'
      fullPath: '/$lang/post/$slug'
      preLoaderRoute: typeof LangPostSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/wiki/': {
      id: '/$lang/wiki/'
      path: '/wiki'
      fullPath: '/$lang/wiki/'
      preLoaderRoute: typeof LangWikiIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/wiki/$slug': {
      id: '/$lang/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/$lang/wiki/$slug'
      preLoaderRoute: typeof LangWikiSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangArchiveRoute: typeof LangArchiveRoute
  LangCreditsRoute: typeof LangCreditsRoute
  LangModrinthRoute: typeof LangModrinthRoute
  LangIndexRoute: typeof LangIndexRoute
  LangPostSlugRoute: typeof LangPostSlugRoute
  LangWikiSlugRoute: typeof LangWikiSlugRoute
  LangWikiIndexRoute: typeof LangWikiIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangArchiveRoute: LangArchiveRoute,
  LangCreditsRoute: LangCreditsRoute,
  LangModrinthRoute: LangModrinthRoute,
  LangIndexRoute: LangIndexRoute,
  LangPostSlugRoute: LangPostSlugRoute,
  LangWikiSlugRoute: LangWikiSlugRoute,
  LangWikiIndexRoute: LangWikiIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  R404Route: R404Route,
  PostSlugRoute: PostSlugRoute,
  WikiSlugRoute: WikiSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
